# info modules
ENABLE_HOST=1
ENABLE_NETWORK=1
ENABLE_SYSTEM=1
ENABLE_RESOURCES=1
ENABLE_SSL_CERTS=1
ENABLE_TOP_PROCESSES=1
ENABLE_STREAK=1
ENABLE_UPTIME_RECORD=1
ENABLE_SERVER_AGE=1
ENABLE_SERVICES=1
ENABLE_ACHIEVEMENTS=0
ENABLE_PROGRESS_BARS=1
ENABLE_ASCII_GRAPH=1
ENABLE_DOCKER=1
ENABLE_SECURITY=1
ENABLE_UPDATES=1
ENABLE_LAST_COMMANDS=0 # broken
ENABLE_FOOTER=0
TOP_PROCESSES_COUNT=3
LAST_COMMANDS_COUNT=5

SHOW_EXTERNAL_IP=1
SHOW_CPU_TEMP=0
SHOW_WEATHER_CITY="Moscow" # tf this made for 🌹🙏

# ssl module
SSL_CERTS_PATH=""
SSL_WARN_DAYS=14


# interface configuration
ENABLE_INTERACTIVE_MENU=1

INTERFACE_MODE=2

THEME_ACCENT="208"
THEME_BG="237"
THEME_BG_ENABLED=1

# helpme module to network
HELPME_PORT=8765
HELPME_BIND="0.0.0.0"

# fuck this.
CTX_MENU_BIND="\C-g"

# safe-rm module
SAFE_RM_LEVEL=2