# info modules
ENABLE_HOST=1
ENABLE_NETWORK=1
ENABLE_SYSTEM=1
ENABLE_RESOURCES=1
ENABLE_SSL_CERTS=1
ENABLE_TOP_PROCESSES=1
ENABLE_STREAK=1
ENABLE_UPTIME_RECORD=1
ENABLE_SERVER_AGE=1
ENABLE_SERVICES=1
ENABLE_ACHIEVEMENTS=0
ENABLE_PROGRESS_BARS=1
ENABLE_ASCII_GRAPH=1
ENABLE_DOCKER=1
ENABLE_SECURITY=1
ENABLE_SSHD_CONFIG=1
ENABLE_UPDATES=1
ENABLE_LAST_COMMANDS=0 # broken
ENABLE_FOOTER=0
ENABLE_NGINX_STATS=1
ENABLE_SCREEN_SESSIONS=1
ENABLE_PACKAGE_UPDATES=1

PACKAGE_UPDATES_LIMIT=5
SHOW_EXTERNAL_IP=1
SHOW_CPU_TEMP=0
SHOW_WEATHER_CITY="Moscow" # tf this made for 🌹🙏

# ssl module
SSL_CERTS_PATH=""
SSL_WARN_DAYS=14


# interface configuration
INTERFACE_MODE=2

THEME_ACCENT="208"
THEME_BG="237"
THEME_BG_ENABLED=1

# helpme module to network
HELPME_PORT=8765
HELPME_BIND="0.0.0.0"

# fuck this.
CTX_MENU_BIND="\C-g"
TOP_PROCESSES_COUNT=3
LAST_COMMANDS_COUNT=5

# safe-rm module
SAFE_RM_LEVEL=2

# nginxstat module
NGINX_STATS_PERIOD_MIN=60
NGINX_STATS_TOP_URLS=5
NGINX_STATS_TOP_IPS=3
NGINX_STATS_LOGS="/var/log/nginx/api-access.log"

# openvpn cfg
ENABLE_OPENVPN=1
# add to /etc/openvpn/server/server.conf 
# management 127.0.0.1 7505

OPENVPN_STATUS_LOG="/var/log/openvpn/openvpn-status.log"
OPENVPN_SERVER_LOG="/var/log/openvpn/openvpn.log"
OPENVPN_DIR="/etc/openvpn/server"
OPENVPN_EASYRSA_DIR="/etc/openvpn/easy-rsa"
OPENVPN_SERVICE="openvpn-server@server"
OPENVPN_IFACE="tun0"
OPENVPN_MGMT_HOST="127.0.0.1"
OPENVPN_MGMT_PORT="7505"

OPENVPN_SPECIAL_CLIENTS="2host|10.8.0.2"